language: node_js
node_js:
 - "6"
 - "7"
 - "8"
 - "9"
 - "10"
install:
- yarn install
script:
- yarn run lint
- yarn run compile
- yarn run test

jobs:
  include:
    - stage: after_success
      script:
      - yarn install
      - yarn run compile
      - yarn run coveralls
      node_js: 9
