language: node_js
node_js:
 - "8"
 - "10"
 - "11"
 - "12"
install:
- yarn install
script:
- yarn run lint
- yarn run compile
- yarn run test

jobs:
  include:
    - stage: after_success
      script:
      - yarn install
      - yarn run test-coverage
      - yarn run send-coveralls
      - yarn add -D codacy-coverage
      - yarn run send-codacy
      node_js: 10
