# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"

version: $(package_version)-{build}

# Install scripts. (runs after repo cloning)
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn install

build_script:
  - yarn run lint
  - yarn run compile

test_script:
  - yarn run test